# Generated by Django 5.1.2 on 2025-09-09 03:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(blank=True, max_length=60)),
                ('state', models.CharField(blank=True, max_length=30)),
                ('country', models.CharField(blank=True, max_length=60)),
                ('capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('owner_name', models.CharField(blank=True, max_length=120)),
                ('owner_email', models.EmailField(blank=True, max_length=254)),
                ('entertainment_manager', models.CharField(blank=True, max_length=120)),
                ('entertainment_email', models.EmailField(blank=True, max_length=254)),
                ('hours', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('is_tour_stop', models.BooleanField(default=False)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('afterparty_info', models.TextField(blank=True)),
                ('meet_greet_info', models.TextField(blank=True)),
                ('published', models.BooleanField(default=False)),
                ('venue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.venue')),
            ],
        ),
    ]
