# Generated by Django 5.1.2 on 2025-09-09 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('role', models.CharField(choices=[('sound', 'Sound'), ('lighting', 'Lighting'), ('guitarist', 'Guitarist'), ('drummer', 'Drummer'), ('engineer', 'Engineer'), ('stagehand', 'Stagehand'), ('other', 'Other')], default='other', max_length=30)),
                ('city', models.CharField(blank=True, max_length=80)),
                ('state', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('rate_cents', models.PositiveIntegerField(default=0, help_text='Per-show rate in cents')),
                ('notes', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='event_media/')),
                ('video_url', models.URLField(blank=True, help_text='YouTube/Vimeo/etc.')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='events.event')),
            ],
        ),
        migrations.CreateModel(
            name='EventEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField(default=1)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='event_reservations', to='equipment.equipment')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_assignments', to='events.event')),
            ],
            options={
                'unique_together': {('event', 'equipment')},
            },
        ),
        migrations.CreateModel(
            name='EventTechAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, help_text='Override role/title for this show', max_length=30)),
                ('rate_cents', models.PositiveIntegerField(default=0)),
                ('confirmed', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tech_assignments', to='events.event')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='events.techperson')),
            ],
            options={
                'unique_together': {('event', 'person')},
            },
        ),
    ]
