# Generated by Django 5.1.2 on 2025-09-09 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_techperson_eventmedia_eventequipment_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventEquipment',
        ),
    ]
