# Generated by Django 5.1.2 on 2025-09-09 08:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_delete_eventequipment'),
        ('pages', '0023_remove_product_category_delete_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistSaleLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('enabled', models.BooleanField(default=True)),
                ('note', models.CharField(blank=True, max_length=120)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_links', to='pages.artist')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artist_links', to='events.event')),
            ],
            options={
                'unique_together': {('event', 'artist')},
            },
        ),
        migrations.CreateModel(
            name='EventArtist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('headliner', 'Headliner'), ('opener', 'Opener'), ('guest', 'Guest')], default='opener', max_length=20)),
                ('set_order', models.PositiveIntegerField(default=0)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='event_slots', to='pages.artist')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artist_slots', to='events.event')),
            ],
            options={
                'ordering': ['set_order', 'id'],
                'unique_together': {('event', 'artist')},
            },
        ),
    ]
