# Generated by Django 5.1.2 on 2025-09-09 23:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_artistsalelink_eventartist'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistLinkHit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('referer', models.URLField(blank=True)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hits', to='events.artistsalelink')),
            ],
            options={
                'indexes': [models.Index(fields=['link', 'at'], name='events_arti_link_id_233a2a_idx')],
            },
        ),
    ]
