# Generated by Django 5.1.2 on 2025-09-14 23:25

from django.db import migrations

DEFAULT_ITEMS = [
    # Your list (kept order)
    "Contact Venue",
    "Confirm Event Date",
    "Confirm Audio Capabilities",
    "Confirm Lighting Capabilities",
    "Book Sound Engineer",
    "Book Lighting Tech",
    "Book Band / Artists",
    "Schedule Rehearsal Dates",
    "Schedule Soundcheck",
    "Create Large Flyer",
    "Create Facebook Banner",
    "Create Facebook Event",
    "Create Instagram Post",
    "Create 2 Facebook Posts",
    "Create 2 TikTok Posts",
    "Create 7 Stories",
    "Get Flyers Printed",
    "Buy Merchandise",
    "Book Vendors",
    "Book Door Person",
    "Book Merchandise Seller",
    "Book Security",
    "Create/Print Poster for Wooden Banner",
    "Buy Audio Equipment (as needed)",
    "Book Photographer",
    "Book Videographer",
    "Venue Visit: Photos & Video",
    "Adjust Rider for Venue",

    # Useful extras
    "Advance with Venue (timeline/tech/hospitality)",
    "Contracts & Deposit (if applicable)",
    "Ticketing Link Live & QA",
    "Run-of-Show / Schedule",
    "Stage Plot/Backline Confirmed",
    "Hospitality & Green Room",
    "Guest List",
    "Parking/Loading Plan",
    "Insurance/COI (if needed)",
    "Emergency Plan / Security Brief",
    "Weather Contingency (if outdoor)",
    "ADA Accessibility Check",
    "Press/Promo Outreach (email list)",
    "Ad Budget & Targeting",
    "Settlement Sheet Template Ready",
    "Card Reader/Cash Float for Merch",
    "Post-Event Content Plan",
]

def seed(apps, schema_editor):
    ChecklistTemplate = apps.get_model("events", "ChecklistTemplate")
    ChecklistTemplateItem = apps.get_model("events", "ChecklistTemplateItem")
    tpl, _ = ChecklistTemplate.objects.get_or_create(name="Default Event Checklist", is_active=True)
    if tpl.items.exists():
        return
    for i, title in enumerate(DEFAULT_ITEMS):
        ChecklistTemplateItem.objects.create(template=tpl, title=title, order=i)

def unseed(apps, schema_editor):
    ChecklistTemplate = apps.get_model("events", "ChecklistTemplate")
    ChecklistTemplate.objects.filter(name="Default Event Checklist").delete()

class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_checklisttemplate_checklisttemplateitem_and_more'),
    ]

    operations = [migrations.RunPython(seed, unseed)]
