# Generated by Django 5.1.2 on 2025-09-17 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_seed_default_checklist'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Wide hero image for the Events page.', null=True, upload_to='events/cover/'),
        ),
        migrations.AddField(
            model_name='event',
            name='flyer',
            field=models.ImageField(blank=True, help_text='Portrait flyer used on cards if no cover.', null=True, upload_to='events/flyer/'),
        ),
    ]
