# Generated by Django 5.1.2 on 2025-11-09 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_event_cover_image_event_flyer'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_21_plus',
            field=models.BooleanField(default=False),
        ),
    ]
