# Generated by Django 5.1.2 on 2025-10-23 05:18

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pages', '0025_alter_artist_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShowSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=160)),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True)),
                ('vibe', models.CharField(choices=[('intimate', 'Intimate'), ('hype', 'Hype/Energetic'), ('mixed', 'Mixed')], default='mixed', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='showsets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('duration_seconds', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('is_collab', models.BooleanField(default=False)),
                ('collab_kind', models.CharField(blank=True, choices=[('headliners', 'Headliners'), ('other', 'Other')], max_length=16)),
                ('collab_other', models.CharField(blank=True, max_length=200)),
                ('genre', models.CharField(blank=True, choices=[('hiphop', 'Hip-Hop'), ('rnb', 'R&B'), ('pop', 'Pop'), ('edm', 'EDM'), ('trap', 'Trap'), ('alt', 'Alt/Indie'), ('other', 'Other')], max_length=12)),
                ('feeling', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('collaborator_artists', models.ManyToManyField(blank=True, related_name='featured_on', to='pages.artist')),
                ('primary_artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='pages.artist')),
            ],
            options={
                'ordering': ['primary_artist__name', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ShowItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort', models.PositiveIntegerField(default=0)),
                ('kind', models.CharField(choices=[('OPENER', 'Opener'), ('HEADLINER', 'Headliner'), ('COLLAB', 'Collaboration'), ('BREAK', 'Break'), ('INTERMISSION', 'Intermission')], max_length=16)),
                ('display_name', models.CharField(blank=True, max_length=200)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('artist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.artist')),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='setbuilder.showset')),
                ('song', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='setbuilder.song')),
            ],
            options={
                'ordering': ['sort', 'id'],
            },
        ),
    ]
