# Generated by Django 5.1.2 on 2026-01-29 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setbuilder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showitem',
            name='kind',
            field=models.CharField(choices=[('OPENER', 'Opener'), ('HEADLINER', 'Headliner'), ('COLLAB', 'Collaboration'), ('BREAK', 'Break'), ('INTERMISSION', 'Intermission'), ('TALKING', 'Talking')], max_length=16),
        ),
    ]
