# Generated by Django 5.1.2 on 2025-09-09 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('category', models.CharField(choices=[('audio', 'Audio'), ('lighting', 'Lighting'), ('stage', 'Stage'), ('video', 'Video'), ('other', 'Other')], default='other', max_length=20)),
                ('serial', models.CharField(blank=True, max_length=120)),
                ('qty_total', models.PositiveIntegerField(default=1)),
                ('notes', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
