# Generated by Django 5.1.2 on 2025-08-28 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_stripeevent_order_orderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('release_type', models.CharField(choices=[('album', 'Album'), ('ep', 'EP'), ('single', 'Single')], max_length=10)),
                ('release_date', models.DateField()),
                ('cover_url', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('links_url', models.URLField(blank=True, help_text='Smartlink/Linktree for this release')),
            ],
            options={
                'ordering': ['-release_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_number', models.PositiveIntegerField(default=1)),
                ('title', models.CharField(max_length=200)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='pages.release')),
            ],
            options={
                'ordering': ['track_number', 'id'],
            },
        ),
    ]
