# Generated by Django 5.1.2 on 2025-08-28 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_release_track'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('youtube_url', models.URLField(help_text='Any YouTube link: watch?v=, youtu.be/, or share URL')),
                ('published_at', models.DateField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=True)),
                ('sort', models.PositiveIntegerField(default=0, help_text='Lower shows first (then newest)')),
            ],
            options={
                'ordering': ['sort', '-published_at', '-id'],
            },
        ),
    ]
