# Generated by Django 5.1.2 on 2025-08-28 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_artist_artistphoto_artistvideo'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('state', models.CharField(blank=True, max_length=10)),
                ('date', models.DateField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=True)),
                ('sort', models.PositiveIntegerField(default=0)),
                ('show', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_albums', to='pages.show')),
            ],
            options={
                'ordering': ['sort', '-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MediaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('photo', 'Photo'), ('video', 'Video')], default='photo', max_length=10)),
                ('image', models.ImageField(blank=True, upload_to='media/album/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('url', models.URLField(blank=True, help_text='YouTube or Vimeo URL (for videos)')),
                ('sort', models.PositiveIntegerField(default=0)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pages.mediaalbum')),
            ],
            options={
                'ordering': ['sort', 'id'],
            },
        ),
    ]
