# Generated by Django 5.1.2 on 2025-08-28 22:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_mediaalbum_mediaitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.CharField(blank=True, max_length=240)),
                ('icon', models.ImageField(blank=True, upload_to='passport/badges/')),
                ('emoji', models.CharField(blank=True, help_text='Fallback icon, e.g. 🌙', max_length=8)),
                ('color', models.CharField(default='#7c5cff', max_length=16)),
                ('points', models.PositiveIntegerField(default=10)),
                ('is_milestone', models.BooleanField(default=False)),
                ('milestone_threshold', models.PositiveIntegerField(blank=True, help_text='Award when user has this many show badges', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShowBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Redeem code (case-insensitive).', max_length=40, unique=True)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='show_links', to='pages.badge')),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passport_badges', to='pages.show')),
            ],
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(default='code', max_length=20)),
                ('acquired_at', models.DateTimeField(auto_now_add=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='earners', to='pages.badge')),
                ('show', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.show')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earned_badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'badge', 'show')},
            },
        ),
    ]
