# Generated by Django 5.1.2 on 2025-08-29 00:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_badge_showbadge_userbadge'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='reated_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
