# Generated by Django 5.1.2 on 2025-08-29 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_product_reated_at_product_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='reated_at',
            new_name='created_at',
        ),
    ]
