# Generated by Django 5.1.2 on 2025-08-29 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_product_is_public'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_public',
        ),
        migrations.AddField(
            model_name='release',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
