# Generated by Django 5.1.2 on 2025-09-05 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_remove_product_is_public_release_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AddField(
            model_name='release',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='releases/'),
        ),
    ]
