# Generated by Django 5.1.2 on 2025-09-05 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_product_image_release_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
