# Generated by Django 5.1.2 on 2025-09-06 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_productimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
