# Generated by Django 5.1.2 on 2025-09-06 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0019_cartitem_unit_price_cents_orderitem_size_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.UniqueConstraint(fields=('cart', 'product', 'variant'), name='uniq_cart_product_variant'),
        ),
    ]
