# Generated by Django 5.1.2 on 2025-09-06 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0020_cartitem_uniq_cart_product_variant'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cartitem',
            name='uniq_cart_product_variant',
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together=set(),
        ),
    ]
