# Generated by Django 5.1.2 on 2025-09-07 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0022_remove_cart_user_remove_cartitem_cart_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
