# Generated by Django 5.1.2 on 2025-09-09 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0023_remove_product_category_delete_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='default_role',
            field=models.CharField(choices=[('headliner', 'Headliner'), ('opener', 'Opener'), ('guest', 'Guest')], default='opener', max_length=20),
        ),
    ]
