# Generated by Django 5.1.2 on 2025-09-12 02:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0024_artist_default_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Headliner account that can edit this EPK.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artist_dashboard', to=settings.AUTH_USER_MODEL),
        ),
    ]
