# Generated by Django 5.1.2 on 2026-01-30 04:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0025_alter_artist_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaalbum',
            name='cover_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cover_for_albums', to='pages.mediaitem'),
        ),
    ]
