# Generated by Django 5.1.2 on 2026-01-30 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_event_is_21_plus'),
        ('pages', '0027_mediasubmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaalbum',
            name='show',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_albums', to='events.event'),
        ),
    ]
