# Generated by Django 5.1.2 on 2026-03-17 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_nfchunt_nfchuntentry'),
        ('events', '0009_event_is_21_plus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nfchunt',
            name='event_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.event'),
        ),
    ]
