# Generated by Django 5.1.2 on 2025-10-04 01:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('rewards', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rewarditem',
            name='fulfill_type',
            field=models.CharField(choices=[('PRODUCT', 'Shop Product'), ('TICKET', 'Ticket Type'), ('COUPON', 'Shop Coupon'), ('CUSTOM', 'Custom/Manual')], default='PRODUCT', max_length=12),
        ),
        migrations.AddField(
            model_name='rewarditem',
            name='quantity_per_redeem',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='rewarditem',
            name='target_ct',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='rewarditem',
            name='target_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='GiftCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=40, unique=True)),
                ('points_cost_override', models.PositiveIntegerField(blank=True, null=True)),
                ('email_restricted', models.EmailField(blank=True, max_length=254)),
                ('notes', models.TextField(blank=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('redeemed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='giftcodes_created', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gift_codes', to='rewards.rewarditem')),
                ('redeemed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rewards.rewardsaccount')),
            ],
        ),
    ]
