# Generated by Django 5.1.2 on 2025-10-04 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0002_rewarditem_fulfill_type_and_more'),
        ('shop', '0002_order_shipped_at_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='redemption',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='redemption',
            name='selected_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.productvariant'),
        ),
        migrations.AddField(
            model_name='redemption',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('FULFILLED', 'Fulfilled'), ('CANCELED', 'Canceled')], default='FULFILLED', max_length=12),
        ),
    ]
