# Generated by Django 5.1.2 on 2025-09-10 06:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0005_artistlinkhit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMetricSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('metro_radius_km', models.PositiveIntegerField(default=80)),
                ('spotify_monthly_listeners', models.IntegerField(blank=True, null=True)),
                ('instagram_local_followers', models.IntegerField(blank=True, null=True)),
                ('tiktok_local_followers', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TechAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('stage_plot', 'Stage Plot'), ('tech_rider', 'Tech Rider'), ('advance', 'Advance')], max_length=40)),
                ('file', models.FileField(upload_to='booking/assets/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EpkVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=64)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('referrer', models.CharField(blank=True, max_length=256)),
                ('utm_source', models.CharField(blank=True, max_length=80)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('venue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='epk_visits', to='events.venue')),
            ],
        ),
        migrations.CreateModel(
            name='FanSupport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('email', models.EmailField(max_length=254)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fan_support', to='events.venue')),
            ],
        ),
        migrations.CreateModel(
            name='ShowInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_start', models.DateField(blank=True, null=True)),
                ('target_end', models.DateField(blank=True, null=True)),
                ('hard_date', models.DateField(blank=True, null=True)),
                ('expected_draw', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(default='pending', max_length=40)),
                ('hold_expires', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='events.venue')),
            ],
        ),
        migrations.CreateModel(
            name='VenueContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=160)),
                ('role', models.CharField(blank=True, max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=80)),
                ('is_primary', models.BooleanField(default=False)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_contacts', to='events.venue')),
            ],
        ),
        migrations.CreateModel(
            name='Outreach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('email', 'Email'), ('call', 'Call')], default='email', max_length=16)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('body', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reply_received', models.BooleanField(default=False)),
                ('next_followup_at', models.DateTimeField(blank=True, null=True)),
                ('followup_notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outreach', to='events.venue')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookingstack.venuecontact')),
            ],
        ),
        migrations.CreateModel(
            name='VenueProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('booking_email', models.EmailField(blank=True, max_length=254)),
                ('booking_name', models.CharField(blank=True, max_length=160)),
                ('booking_phone', models.CharField(blank=True, max_length=80)),
                ('genre_fit', models.CharField(blank=True, max_length=160)),
                ('website_override', models.URLField(blank=True)),
                ('last_lineup_scrape', models.DateTimeField(blank=True, null=True)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_profile', to='events.venue')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('venue',), name='ux_venueprofile_venue_one')],
            },
        ),
    ]
