# Generated by Django 5.1.2 on 2025-09-10 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingstack', '0001_initial'),
        ('events', '0005_artistlinkhit'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenerMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_name', models.CharField(max_length=160)),
                ('contact_url', models.URLField(blank=True)),
                ('last_seen', models.DateField(blank=True, null=True)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opener_map', to='events.venue')),
            ],
            options={
                'indexes': [models.Index(fields=['venue', 'artist_name'], name='bookingstac_venue_i_d907ce_idx')],
            },
        ),
    ]
