# Generated by Django 5.1.2 on 2025-09-11 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookingstack', '0002_openermap'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venueprofile',
            options={'verbose_name': 'Venue Profile', 'verbose_name_plural': 'Venue Profiles'},
        ),
        migrations.RemoveField(
            model_name='venueprofile',
            name='capacity',
        ),
    ]
