# Generated by Django 5.1.2 on 2025-09-11 01:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingstack', '0003_alter_venueprofile_options_and_more'),
        ('events', '0005_artistlinkhit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venueprofile',
            name='venue',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='booking_profile', to='events.venue'),
        ),
    ]
