# Generated by Django 5.1.2 on 2026-03-25 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0002_emailcampaign_emailcampaignrecipient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailcampaignrecipient',
            name='full_name',
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='event_id_snapshot',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emailcampaignrecipient',
            name='first_name',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='emailcampaignrecipient',
            name='last_name',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='is_subscribed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='unsubscribe_token',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='unsubscribed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emailcampaign',
            name='audience_type',
            field=models.CharField(choices=[('subscribers', 'Subscribers'), ('ticket_buyers', 'Ticket Buyers')], max_length=30),
        ),
        migrations.AlterField(
            model_name='emailcampaign',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('sending', 'Sending'), ('sent', 'Sent'), ('partial', 'Partial'), ('failed', 'Failed')], default='draft', max_length=20),
        ),
    ]
