# Generated by Django 5.1.2 on 2025-09-09 04:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_ticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('fulfilled', models.BooleanField(default=False)),
                ('stripe_session_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('purchaser_email', models.EmailField(blank=True, max_length=254)),
                ('ticket_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='tickets.tickettype')),
            ],
            options={
                'indexes': [models.Index(fields=['stripe_session_id'], name='tickets_tic_stripe__0afa44_idx')],
            },
        ),
    ]
