# Generated by Django 5.1.2 on 2025-09-09 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_ticketreservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickettype',
            name='max_per_order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
