# Generated by Django 5.1.2 on 2025-09-09 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_tickettype_max_per_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketreservation',
            name='purchaser_name',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
