# Generated by Django 5.1.2 on 2025-09-09 07:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0023_remove_product_category_delete_category_and_more'),
        ('tickets', '0005_ticketreservation_purchaser_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Card/Stripe'), ('cash', 'Cash'), ('comp', 'Comp')], default='card', max_length=10),
        ),
        migrations.AddField(
            model_name='ticket',
            name='sold_by_artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_sold', to='pages.artist'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='sold_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_issued', to=settings.AUTH_USER_MODEL),
        ),
    ]
